layout_spectrum: 0.011158656794577837
typography_spectrum: 0.3664316351059824
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.6378999361768365
  lightness: 0.32380042038857937
  saturation: 0.13630810868926346
  rhythmicContrast: 0.7000183761119843
name: OperaticData
favicon: null
title: Making your data sing!
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
