name: OperaticData
favicon: null
layout_spectrum: 0.08033433533273637
typography_spectrum: 0.41166
title: 'Making your data sing!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
