name: OperaticData
favicon: null
layout_spectrum: 0.08033433533273637
typography_spectrum: 0.41166
title: 'Making your data sing!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1604'
    - '#6b5f35'
    - '#cbbd98'
    - '#918a5c'
    - '#fdfebe'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
